package estudianteApp;


/**
* estudianteApp/estudianteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from estudiante.idl
* miércoles 8 de mayo de 2019 09:30:13 PM COT
*/

public interface estudianteOperations 
{
  boolean insertarEstudiante (int idestudiante, String nombreEstudiante, String apellidoEstudiante, int carrera);
  String consultaEstudiante (int idestudiante);
  boolean actualizarEstudiante (int idestudiante, String nombreEstudiante, String apellidoEstudiante, int carrera);
  boolean eliminarEstudiante (int idestudiante);
  String listarEstudiantes ();
  void shutdown ();
} // interface estudianteOperations
