package estudianteApp;

/**
* estudianteApp/estudianteHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from estudiante.idl
* miércoles 8 de mayo de 2019 09:30:13 PM COT
*/

public final class estudianteHolder implements org.omg.CORBA.portable.Streamable
{
  public estudianteApp.estudiante value = null;

  public estudianteHolder ()
  {
  }

  public estudianteHolder (estudianteApp.estudiante initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = estudianteApp.estudianteHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    estudianteApp.estudianteHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return estudianteApp.estudianteHelper.type ();
  }

}
