package estudianteApp;


/**
* estudianteApp/estudiante.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from estudiante.idl
* miércoles 8 de mayo de 2019 09:30:13 PM COT
*/

public interface estudiante extends estudianteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface estudiante
